name: Build Bootc Images
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.brand_name}}-${{ inputs.stream_name }}
  cancel-in-progress: true

jobs:
  build-base:
    name: Build Base Container
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
    with:
      build_target: base

  build-nginx:
    name: Build Nginx Container
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
    with:
      build_target: nginx

  build-k3s-server:
    name: Build K3s Server Container
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
    with:
      build_target: k3s-server

  build-k3s-agent:
    name: Build K3s Agent Container
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
    with:
      build_target: k3s-agent

  