name: Build Bootc Images
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 10 * * 0'  # 10:05am UTC every Sunday
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.brand_name}}-${{ inputs.stream_name }}
  cancel-in-progress: true

jobs:
  build-base:
    name: Build Base Image
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
    with:
      build_target: base

  build-nginx:
    name: Build Nginx Image
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
    with:
      build_target: nginx

  # build-k3s-server:
  #   name: Build K3s Server Image
  #   uses: ./.github/workflows/reusable-build-image.yml
  #   secrets: inherit
  #   strategy:
  #     fail-fast: false
  #   with:
  #     build_target: k3s-server
  #     containerfile: ./k3s/day2/Containerfile

  # build-k3s-agent:
  #   name: Build K3s Agent Image
  #   uses: ./.github/workflows/reusable-build-image.yml
  #   secrets: inherit
  #   strategy:
  #     fail-fast: false
  #   with:
  #     build_target: k3s-agent
  #     containerfile: ./k3s/day2/Containerfile

  build-prometheus:
    name: Build Prometheus Image
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
    with:
      build_target: prometheus

  build-nas:
    name: Build NAS Image
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
    with:
      containerfile: ./nas/Containerfile
