name: Build Bootc Artifact
on:
  pull_request:
    branches:
      - main
    paths:
      - './.github/workflows/build-artifact.yml'
  workflow_dispatch:
    inputs:
      build_type:
        description: 'The type of artifact to create from your bootc image'
        type: choice
        required: true
        options:
          - "ami"
          - "qcow2"
          - "vmdk"
          - "anaconda-iso"
          - "raw"
          - "vhd"
          - "gce"

env:
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository }}/base"
  DEFAULT_TAG: "latest"

jobs:
  build:
    name: Build ISOs
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@d0603cd0a7dd490be678164909f65c7737470a7f # v6
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      # - name: Maximize build space
      #   if: inputs.platform != 'arm64'
      #   uses: ublue-os/remove-unwanted-software@cc0becac701cf642c8f0a6613bbdaf5dc36b259e # v9
      #   with:
      #     remove-codeql: true

      - name: Login to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create output directory
        run: mkdir output

      - name: Pull Image
        run: |
          sudo podman pull ${{ steps.registry_case.outputs.lowercase }}:${{ env.DEFAULT_TAG }}

      - name: Build bootable image using bootc-image-builder
        run: |
          sudo podman run --rm --privileged --pull=newer --security-opt label=type:unconfined_t \
            -v ${{ github.workspace }}/output:/output -v /var/lib/containers/storage:/var/lib/containers/storage \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type ${{ github.event.inputs.build_type }} \
            ${{ steps.registry_case.outputs.lowercase }}:${{ env.DEFAULT_TAG }}

      - name: Upload Bootable Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bootc-image-${{ github.event.inputs.build_type }}
          path: ${{ github.workspace }}/output/*
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true         